print("Hi. I'm the computer.")
name = input("What's your name?")
color = input(f"Hi {name}! What's your favorite color?")
print(f"No way! My favorite color is also {color}!")
movie = input("whats your favorite movie?")
print(f"What!?! My favorite movie is also {movie}!")
game = input("What is your favorite game?")
print(f"Get out of here! My favorite game is {game}, too!")
topping = input("what is your LEAST favorite pizza topping?")
print(f"I dislike {topping} on my pizza! Just like you!")
subject = input("What is your favorite class?")
print(f"wow! My favorite class is {subject}, as well!")
print("We like all the same things! We should become best friends!")